baseURL = "https://darkpro1337.github.io/discord-webhooks/"
languageCode = "en-us"
title = "Discord Webhooks Guide"
theme = "hugo-theme-learn"
publishDir = "docs"
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author = "DarkPro1337"
description = ""
showVisitedLinks = true
disableLanguageSwitchingButton = true
themeVariant = "mine"
disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Оригинал"
identifier = "og"
url = "https://birdie0.github.io/discord-webhooks-guide/"
weight = 5

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github репо"
identifier = "ds"
url = "https://github.com/DarkPro1337/discord-webhooks"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-telegram-plane'></i> Написать автору"
identifier = "tg"
url = "https://telegram.me/DarkPro1337"
weight = 15
